name: desafio
description: Desafio para Cappta

publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^4.2.0
  http: ^0.13.4
  table_calendar: ^3.0.3
  freezed_annotation: ^1.0.0
  state_notifier: ^0.7.1
  intl: ^0.17.0
  flutter_lid: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  freezed: ^1.0.0

flutter:
  uses-material-design: true